export interface Devi {
  id: number;
  name: string;
  shaktiPeetha: string;
  location: string;
  description: string;
  color: string;
}

export const devis: Devi[] = [
  {
    id: 1,
    name: 'Mahalakshmi',
    shaktiPeetha: 'Kolhapur, Maharashtra',
    location: 'Maharashtra',
    description: 'Goddess of wealth, fortune, and prosperity, seated on a pink lotus.',
    color: '#E8B830',
  },
  {
    id: 2,
    name: 'Mahadurga',
    shaktiPeetha: 'Vaishno Devi',
    location: 'Jammu & Kashmir',
    description: 'The invincible warrior goddess who rides a lion and wields weapons.',
    color: '#D63648',
  },
  {
    id: 3,
    name: 'Mahakali',
    shaktiPeetha: 'Ujjain, Madhya Pradesh',
    location: 'Madhya Pradesh',
    description: 'The fierce destroyer of evil, dark-complexioned, standing on Lord Shiva.',
    color: '#3D2B5E',
  },
  {
    id: 4,
    name: 'Mahasaraswati',
    shaktiPeetha: 'Sharada / Kashmir',
    location: 'Jammu & Kashmir',
    description: 'Goddess of knowledge, wisdom, and arts, playing the veena, riding a swan.',
    color: '#F5F0E8',
  },
  {
    id: 5,
    name: 'Mahaparvati',
    shaktiPeetha: 'Various Parvati traditions',
    location: 'Pan-India',
    description: 'The divine mother of the Himalayas, consort of Lord Shiva.',
    color: '#2E9B8F',
  },
  {
    id: 6,
    name: 'Kamakhya',
    shaktiPeetha: 'Guwahati, Assam',
    location: 'Assam',
    description: 'Tantric goddess of desire and creation, the bleeding goddess of Assam.',
    color: '#C73E5A',
  },
  {
    id: 7,
    name: 'Kamakshi',
    shaktiPeetha: 'Kanchipuram, Tamil Nadu',
    location: 'Tamil Nadu',
    description: 'The goddess whose eyes are full of love, holding a sugarcane bow and arrows.',
    color: '#F0A04B',
  },
  {
    id: 8,
    name: 'Bhramaramba',
    shaktiPeetha: 'Srisailam, Andhra Pradesh',
    location: 'Andhra Pradesh',
    description: 'Goddess in the form of a bee, the divine mother of Srisailam.',
    color: '#6B4F8E',
  },
  {
    id: 9,
    name: 'Chamundeshwari',
    shaktiPeetha: 'Mysuru, Karnataka',
    location: 'Karnataka',
    description: 'Slayer of demons Chanda and Munda, riding a lion on Chamundi Hill.',
    color: '#A63332',
  },
  {
    id: 10,
    name: 'Jogulamba',
    shaktiPeetha: 'Alampur, Telangana',
    location: 'Telangana',
    description: 'Fierce goddess with scorpion symbolism, one of the Ashtadasha Shakti Peethas.',
    color: '#7A5C3A',
  },
  {
    id: 11,
    name: 'Vishalakshi',
    shaktiPeetha: 'Varanasi, Uttar Pradesh',
    location: 'Uttar Pradesh',
    description: 'The large-eyed goddess worshipped at the sacred ghats of the Ganges.',
    color: '#D4762A',
  },
  {
    id: 12,
    name: 'Mangala Gauri',
    shaktiPeetha: 'Gaya, Bihar',
    location: 'Bihar',
    description: 'The auspicious four-armed goddess, worshipped for wellbeing and fortune.',
    color: '#E87B9E',
  },
  {
    id: 13,
    name: 'Jwalamukhi',
    shaktiPeetha: 'Kangra, Himachal Pradesh',
    location: 'Himachal Pradesh',
    description: 'The flaming goddess, where eternal blue flames burn from the rock as her tongue.',
    color: '#FF6B35',
  },
  {
    id: 14,
    name: 'Manikyamba',
    shaktiPeetha: 'Draksharamam, Andhra Pradesh',
    location: 'Andhra Pradesh',
    description: 'The ruby-hued goddess, with precious gem symbolism at Draksharamam.',
    color: '#B8336A',
  },
  {
    id: 15,
    name: 'Puruhutika',
    shaktiPeetha: 'Pithapuram, Andhra Pradesh',
    location: 'Andhra Pradesh',
    description: 'Goddess who fulfills all desires, the beloved deity of Pithapuram.',
    color: '#3A7CA5',
  },
  {
    id: 16,
    name: 'Biraja',
    shaktiPeetha: 'Jajpur, Odisha',
    location: 'Odisha',
    description: 'Fierce goddess with a spear, riding a buffalo, the presiding deity of Jajpur.',
    color: '#C44536',
  },
  {
    id: 17,
    name: 'Ekaveerika',
    shaktiPeetha: 'Mahur, Maharashtra',
    location: 'Maharashtra',
    description: 'Fierce form of the goddess Renuka, mother of Parashurama, at Mahur.',
    color: '#5B7553',
  },
  {
    id: 18,
    name: 'Lalita Madhaveshwari',
    shaktiPeetha: 'Prayagraj, Uttar Pradesh',
    location: 'Uttar Pradesh',
    description: 'The beautiful playful goddess, consort of Madhava, at the Triveni Sangam.',
    color: '#D4A537',
  },
];
